version: '3.8'

services:
  db:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/todo_db
      - QUARKUS_DATASOURCE_USERNAME=todo_user
      - QUARKUS_DATASOURCE_PASSWORD=todo_pass
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["java", "-jar", "build/quarkus-app/quarkus-run.jar"]
volumes:
  pgdata:
